items:
  - name: Find Relays
    slug: find
    href: '#/relays/find'
    group: tools
  - name: Statistics
    slug: statistics
    href: '#/relays/statistics'
    group: tools
  - name: Interactive Map
    slug: map
    href: '#/relays/map'
    group: tools