items:
  - name: Find Relays
    slug: find-relays
    href: '#'
    group: tools
  - name: Statistics
    slug: network
    href: '#'
    group: tools
  - name: Interactive Map
    slug: map
    href: '#'
    group: tools